name: Bylickilabs Generate Snake
 
on:
  schedule:
    - cron: "0 */1 * * *" 

  workflow_dispatch:
  
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: tintommy
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Show build status
        run: git status
        
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
